# Book settings

title: The Data Science Odyssey
subtitle: Mastering Programming, Analytics, Machine Learning, and Cloud
author: Romeo Silvestri
copyright: "2023" 
logo: logo.png
exclude_patterns: ["cache"]


# Information about where the book exists on the web
repository:
  url: https://github.com/RomeoSilvestri/Data_Science-Book
  path_to_book: ""
  branch: main


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex


# Execution of notebooks
execute:
  execute_notebooks: "force"  # Force execution of notebooks at build time
  cache: "off"  # Turn off caching
  

# HTML-specific settings
html:
  favicon                   : "logo.png"  # A path to a favicon image
  navbar_number_sections    : false  # Add a number to each section in your left navbar
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : false  # Whether to add an "open an issue" button
  extra_navbar              : <a href="https://www.linkedin.com/in/romeo-silvestri/">Romeo Silvestri</a>  # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://romeosilvestri.github.io/Data_Science-Book/.html"  # The base URL where your book will be hosted